name: Github Actions
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    outputs:
      text: ${{ steps.finished.outputs.text }}
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Build Project
        run: yarn && yarn build
      - name: Deploying the Project
        run: yarn deploy
      - name: Setup Finish
        id: finished
        run: echo "::set-output name=text::hello-world-from-build-job"
  test-app:
    needs: build-app
    runs-on: ubuntu-latest
    env:
      MY_JOB_OUTPUT: ${{ needs.build-app.outputs.text }}
    steps:
      - run: echo $MY_JOB_OUTPUT
